### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'pretrained_resource'

### ISSUE THREAD

**Issue by chaoji90** [zhyever/PatchFusion#34]
`AttributeError: 'dict' object has no attribute 'pretrained_resource' `occurred when I executed `model = PatchFusion.from_pretrained(model_name).to(DEVICE).eval()
`
It looks like the dictionary is accessed through dots. Any suggestions on how to deal with it? Is it a version problem?

**Comment by zhyever** [comment]
Tbh, I have no idea about this issue. Anyone has a similar case and can help?

**Comment by graysuit** [comment]
@zhyever 
I have same issue. Its on:
https://github.com/zhyever/PatchFusion/blob/main/estimator/models/patchfusion.py#L77

```c#

C:\Users\gray\Desktop\PatchFusion\tools>test_single_forward.py
config.json: 100%|██████████████████████████████████████████████████████████████████| 3.65k/3.65k [00:00<00:00, 3.64MB/s]
C:\Users\gray\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\gray\.cache\huggingface\hub\models--Zhyever--patchfusion_depth_anything_vitl14. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Traceback (most recent call last):
  File "C:\Users\gray\Desktop\PatchFusion\tools\test_single_forward.py", line 12, in <module>
    model = PatchFusion.from_pretrained(model_name).to(DEVICE).eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gray\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gray\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\hub_mixin.py", line 511, in from_pretrained
    instance = cls._from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gray\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\hub_mixin.py", line 727, in _from_pretrained
    model = cls(**model_kwargs)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gray\Desktop\PatchFusion\tools\estimator\models\patchfusion.py", line 77, in __init__
    config.coarse_branch.pretrained_resource = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'pretrained_resource'

C:\Users\gray\Desktop\PatchFusion\tools>
```

**Comment by zhyever** [comment]
While I don't know what is going on, one hack implementation is as simple as replacing this `config.coarse_branch.pretrained_resource = None` with `config.coarse_branch['pretrained_resource'] = None`. L78 should be similar. I'm not sure if there are more bugs after these two lines of codes.

Btw, I recommand to check the installed huggingface_hub version and align it with our offical one `huggingface-hub==0.20.1`

**Comment by graysuit** [comment]
Sorry if it looks dump
I'm new to huggingface etc things
and I copied estimator etc folders to tools directory
Does that affect ?

My purpose is to create high resolution depth map image from an image
and after generating 3d relief sculpture stl
for that I'm also planning to bundle into pyinstaller
Will it work and am I in right direction ?
Currently using dotnet (C#/VB) as main language and trying to wrap it, as dotnet doesn't have such libs

**Comment by zhyever** [comment]
No worries. This interface is somehow annoying because it's changing some detailed implementations during updates...

It would affect if you change the folder structure. Please leave them there. (as far as I see)

The current issue is that the `huggingface-hub` might not work on purpose, so it would be impossible to download everything automatically in your case. The solution is to use another way to build the model locally but it might need more manual work (download checkpoints, change configs, etc). I will first try to do it on my machine and then publish another `test_single_forward_wo_net.py` later. No worries, it would be friendly to people who are new to these tricky stuffs.

I'm not sure if the path after getting high resolution depth map is correct. But I believe patchfusion is always a good choice for high resolution metric depth estimation. Feel free to have a try and hopefully everything goes well and you can finally achieve your goals!

**Comment by graysuit** [comment]
Hi, truly appreciate your help
I tried refactoring like you suggested and errors gone.


Now I supplied it 500x500px image, but my pc got hang up:
![image](https://github.com/zhyever/PatchFusion/assets/54432616/1406a48e-dbda-46ee-8cc8-083e0183944d)

```
xFormers not available
xFormers not available
C:\Users\gray\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3588.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```

Not sure if PatchFusion does heavy calculations ? and isn't suitable for general CPU ?
I have 8gb ram, core i3

**Comment by zhyever** [comment]
Hi, glad to hear it works. We recommand to use gpu to run patchfusion. It's kind of heavy for cpu

**Comment by graysuit** [comment]
> Hi, glad to hear it works. We recommand to use gpu to run patchfusion. It's kind of heavy for cpu

No issue, I can use my friend's PC

I tried [demo](https://huggingface.co/spaces/zhyever/PatchFusion).
But output seems low detailed compared to samples on [paper](https://zhyever.github.io/patchfusion).


For example I tried horse image 1500px square.
![input - Copy](https://github.com/zhyever/PatchFusion/assets/54432616/ba914d78-3036-4248-8cf8-745e99ef1262)

But output didn't have details like eye, nose etc.
![clipimage](https://github.com/zhyever/PatchFusion/assets/54432616/fb5728b5-3905-4083-a185-d827fd62d8f5)
I was expecting output which could be made like below:
![image](https://github.com/zhyever/PatchFusion/assets/54432616/7e19cf88-418d-4557-8364-571538083790)


Is there any settings I need to change.
Also after that, will I able to generate 3D model ?
For example this sample looks very good. I consider brightness as Z and constructed 3D STL model and looks to be working.
Not sure if its correct way and have any recommendations ?
![clipimage](https://github.com/zhyever/zhyever.github.io/blob/main/patchfusion/images/interactive/case3_pf.png?raw=true)

![image](https://github.com/zhyever/PatchFusion/assets/54432616/3f3e8372-617a-48c7-b020-f283ae4bd878)

**Comment by zhyever** [comment]
Sorry for the late reply!

It might be too hard for the model to predict depth for this figure. It could be out-of-distribution in some sense. Please let me know if you find a way to get better results. Really interested in a successful solution.

**Comment by graysuit** [comment]
> Please let me know if you find a way to get better results. Really interested in a successful solution.

Unfortunately, I'm not working on project anymore.
But best clean results were generated from [vistasculpt](https://vistasculpt.com).
I analyzed its working, it was using [dinov2](https://dinov2.metademolab.com/demos?category=depth)
I failed to know mechanism though.

![image](https://github.com/user-attachments/assets/ad017eb7-06da-45fb-a866-05c7800433d1)
I attached output stl, you can check: [horse.zip](https://github.com/user-attachments/files/16488614/horse.zip)
